Bài 1: Chuẩn hóa dữ liệu (Min-Max Scaling)
Mô tả: Bạn có tập dữ liệu về doanh số hàng ngày [100, 200, 150, 400, 250]. Hãy chuẩn hóa dữ liệu này về khoảng [0,1] bằng Min-Max Scaling.

Yêu cầu:
Tạo mảng dữ liệu.
Áp dụng công thức chuẩn hóa: x' = (x-min(x))/(max(x)-min(x))

Đáp án mẫu:
import numpy as np
sales = np.array([100, 200, 150, 400, 250])
normalized_sales = (sales - np.min(sales)) / (np.max(sales) - np.min(sales))
print("Chuẩn hóa Min-Max:", normalized_sales)

In [3]:
import numpy as np
rev = np.array([100, 200, 150, 400, 250])
# Chuẩn hóa data bằng Min-Max Scaling
rev_2 = (rev - np.min(rev)) / (np.max(rev) - np.min(rev))
print(rev_2)

[0.         0.33333333 0.16666667 1.         0.5       ]


Bài 2: Tính tổng doanh thu theo từng tháng
Mô tả: Bạn có doanh thu theo từng ngày trong 3 tháng (30 ngày mỗi tháng), được lưu trong một mảng 1D có 90 phần tử. Hãy tính tổng doanh thu của mỗi tháng.

Yêu cầu:
Tạo mảng ngẫu nhiên gồm 90 ngày (randint(100, 500)).
Reshape thành (3, 30).
Tính tổng theo từng tháng (axis=1).

Đáp án mẫu:
import numpy as np
rev_arr = np.random.randint(100, 500, size=(3, 30))  # Tạo luôn mảng 2D
monthly_total_rev = np.sum(rev_arr, axis=1)
print(monthly_total_rev)

In [19]:
import numpy as np
'''Cách cũ - Đúng về logic nhưng chưa tối ưu: 
import random
rev = [] #Tạo danh sách rỗng chứa data doanh thu từng ngày trong 3 tháng 
for _ in range(90): #Gen ngẫu nhiên doanh thu cho từng ngày (tổng 90 ngày
    # rev.append(random.randint(100, 500)) 
rev_arr = np.array(rev) #Chuyển đổi danh sách thành mảng array
rev_1d = rev_arr.reshape(3,30) #Công thức: array.reshape(hàng, cột)'''
rev_1d = np.random.randint(100, 500, 90).reshape(3, 30)  # Tạo mảng và reshape trong 1 bước
monthly_total_rev = np.sum(rev_1d, axis=1) #Tính tổng theo hàng ngang aka 'rev mỗi tháng'
print(monthly_total_rev)

[9115 9502 9152]


Bài 3: Xác định sản phẩm bán chạy nhất
Mô tả: Bạn có dữ liệu doanh số của 5 sản phẩm qua 7 ngày (mảng 2D 5x7). Hãy tìm sản phẩm có tổng doanh số cao nhất.

Yêu cầu:
Tạo mảng ngẫu nhiên (5,7).
Tính tổng doanh số theo từng sản phẩm.
Xác định sản phẩm bán chạy nhất (dùng np.argmax()).

Đáp án mẫu:
import numpy as np
np.random.seed(42)
sales = np.random.randint(50, 300, size=(5, 7))
total_sales_per_product = np.sum(sales, axis=1)
best_selling_product = np.argmax(total_sales_per_product)
print("Doanh số từng sản phẩm:", total_sales_per_product)
print("Sản phẩm bán chạy nhất (index):", best_selling_product)

In [36]:
import numpy as np
sales_2d = np.random.randint(50,300, 35).reshape(5,7) # Tạo mảng và reshape trong 1 bước
total_sales_per_product = np.sum(sales_2d, axis=1) #Tính tổng theo hàng ngang
best_sales_product = np.argmax(total_sales_per_product, axis=None) #Tìm vị trí index của phần tử lớn nhất trong toàn bộ mảng 1D
for _ in range (5):
    print(f'{sales_2d[_]} | Total: {total_sales_per_product[_]}')
print(f'Best sales index: {best_sales_product}')

[200 208 271  91 148  56 193] | Total: 1167
[139 161 298 293 109 162  51] | Total: 1213
[178  97 189 246  86 209 296] | Total: 1301
[ 58 282 148 196  97 257 180] | Total: 1218
[197 201 103 169 210 201 165] | Total: 1246
Best sales index: 2


Bài 4: Phát hiện dữ liệu bị thiếu
Mô tả: Một bảng dữ liệu có thể chứa giá trị bị thiếu (np.nan). Hãy tìm số lượng giá trị bị thiếu trong mảng 2D (5x5).

Yêu cầu:
Tạo mảng 2D (5x5) chứa một số phần tử bị thiếu (np.nan).
Đếm số lượng phần tử bị thiếu bằng np.isnan().sum().

Đáp án mẫu:
import numpy as np
data = np.array([[1, 2, np.nan, 4, 5],
                 [6, np.nan, 8, 9, 10],
                 [11, 12, 13, 14, np.nan],
                 [16, 17, 18, 19, 20],
                 [np.nan, 22, 23, 24, 25]])

missing_values = np.isnan(data).sum()
print("Số lượng giá trị bị thiếu:", missing_values)

In [38]:
import numpy as np
# Mảng array 5x5 với một số phần tử chứa giá trị bị thiếu (np.nan)
data = np.array([[1, 2, np.nan, 4, 5],
                 [6, np.nan, 8, 9, 10],
                 [11, 12, 13, 14, np.nan],
                 [16, 17, 18, np.nan, 20],
                 [np.nan, 22, 23, 24, 25]])
# Đếm số lượng các phần tử np.nan:
nan_counter = np.sum(np.isnan(data))
print(nan_counter)

5


Bài 5: Xử lý dữ liệu bị thiếu
Mô tả: Bạn có một tập dữ liệu chứa np.nan. Hãy thay thế các giá trị nan bằng trung bình của cột đó.

Yêu cầu:

Tạo mảng chứa np.nan.
Tính trung bình theo cột, bỏ qua np.nan.
Thay thế nan bằng trung bình.

Đáp án mẫu:
import numpy as np
data = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_means = np.nanmean(data, axis=0)
indices = np.where(np.isnan(data))
data[indices] = np.take(col_means, indices[1])
print("Dữ liệu sau khi thay thế NaN:\n", data)

In [5]:
import numpy as np

# Tạo mảng chứa NaN
data = np.array([[1, np.nan, 3], 
                 [np.nan, 4, 5], 
                 [6, 7, 8]])

# Tính trung bình mỗi cột, bỏ qua NaN
column_nanmean = np.nanmean(data, axis=0)

# Tìm vị trí các phần tử NaN
nan_location = np.where(np.isnan(data))

# Thay thế NaN bằng giá trị trung bình cột tương ứng
data[nan_location] = np.take(column_nanmean, nan_location[1])

# In kết quả
print("Dữ liệu sau khi thay thế NaN:\n", data)

Dữ liệu sau khi thay thế NaN:
 [[1.  5.5 3. ]
 [3.5 4.  5. ]
 [6.  7.  8. ]]


Bài 6: Xếp hạng doanh số
Mô tả: Bạn có doanh số của 6 sản phẩm [400, 800, 300, 700, 500, 600]. Hãy xếp hạng theo thứ tự giảm dần (1 là cao nhất).

Yêu cầu:
Tạo mảng doanh số.
Sắp xếp theo thứ tự giảm dần.
Dùng np.argsort() để tạo bảng xếp hạng.

Đáp án mẫu:
import numpy as np
sales = np.array([400, 800, 300, 700, 500, 600])
ranking = np.argsort(-sales) + 1
print("Xếp hạng doanh số:", ranking)

In [10]:
import numpy as np
sales = np.array([400, 800, 300, 700, 500, 600])
xep_hang = np.argsort(-sales) + 1 # Sắp xếp theo thứ tự giảm dần và +1 để thành xếp hạng bắt đầu từ 1
print(xep_hang)

[2 4 6 5 1 3]


Bài 7: Tính giá trị trung vị (Median)
Mô tả: Hãy tìm trung vị của một danh sách lương nhân viên [700, 800, 1200, 1500, 1800, 5000, 6000].

Yêu cầu:

Tạo mảng lương.
Dùng np.median() để tính trung vị.

Đáp án mẫu:
import numpy as np
salaries = np.array([700, 800, 1200, 1500, 1800, 5000, 6000])
median_salary = np.median(salaries)
print("Mức lương trung vị:", median_salary)

In [11]:
import numpy as np
salary_arr = np.array([700, 800, 1200, 1500, 1800, 5000, 6000])
salary_median = np.median(salary_arr)
print(salary_median)

1500.0


Bài 8: Lọc dữ liệu theo điều kiện
Mô tả: Bạn có một danh sách khách hàng với số lần mua hàng [2, 5, 8, 1, 10, 7, 3, 6]. Hãy tìm những khách hàng có số lần mua trên 5.

Yêu cầu:
Tạo mảng dữ liệu.
Dùng boolean indexing để lọc khách hàng.

Đáp án mẫu: import numpy as np
purchases = np.array([2, 5, 8, 1, 10, 7, 3, 6])
high_value_customers = purchases[purchases > 5]
print("Khách hàng có trên 5 lần mua hàng:", high_value_customers)


In [2]:
import numpy as np
purchases = np.array([2, 5, 8, 1, 10, 7, 3, 6])
high_value_customers = purchases[purchases > 5] # Sử dụng boolean indexing để lọc khách hàng có số lần mua > 5
print(high_value_customers)

[ 8 10  7  6]


Bài 9: Tính ma trận hiệp phương sai (Covariance)
Mô tả: Bạn có dữ liệu doanh thu của hai sản phẩm trong 5 ngày [100, 200, 300, 400, 500] và [50, 100, 150, 200, 250]. Hãy tính ma trận hiệp phương sai (covariance matrix).

Yêu cầu:
Tạo hai mảng doanh thu.
Dùng np.cov() để tính ma trận hiệp phương sai.

Đáp án mẫu:
import numpy as np
product_A = np.array([100, 200, 300, 400, 500])
product_B = np.array([50, 100, 150, 200, 250])
cov_matrix = np.cov(product_A, product_B)
print("Ma trận hiệp phương sai:\n", cov_matrix)

In [3]:
import numpy as np
product_A = np.array([100, 200, 300, 400, 500])
product_B = np.array([50, 100, 150, 200, 250])

# Tính ma trận hiệp phương sai
cov_matrix = np.cov(product_A, product_B)
print(cov_matrix)


[[25000. 12500.]
 [12500.  6250.]]


Bài 10: Ma trận tương quan (Correlation Matrix)
Mô tả: Hãy tính ma trận tương quan giữa hai danh sách doanh thu giống bài trên, dùng np.corrcoef().

Đáp án mẫu:
import numpy as np
corr_matrix = np.corrcoef(product_A, product_B)
print("Ma trận tương quan:\n", corr_matrix)

In [4]:
import numpy as np
product_A = np.array([100, 200, 300, 400, 500])
product_B = np.array([50, 100, 150, 200, 250])

# Tính ma trận tương quan
corr_matrix = np.corrcoef(product_A, product_B)
print(corr_matrix)


[[1. 1.]
 [1. 1.]]
