📌 10 bài tập NumPy cho Data Analyst
Bài 1: Tạo mảng doanh thu hàng tuần
Mô tả: Bạn là Data Analyst tại một cửa hàng. Tạo mảng 1D từ dữ liệu doanh thu tuần (triệu đồng): [5, 7, 3, 8, 6].
Yêu cầu:
Tạo mảng bằng np.array().
In mảng và kiểm tra kiểu dữ liệu (dtype).
Đáp án mẫu:

import numpy as np
doanh_thu = np.array([5, 7, 3, 8, 6])
print("Doanh thu:", doanh_thu)
print("Kiểu dữ liệu:", doanh_thu.dtype)

In [2]:
import numpy as np
doanh_thu_tuan = np.array([5, 7, 3, 8, 6])
print(doanh_thu_tuan)
print(doanh_thu_tuan.dtype)

[5 7 3 8 6]
int32


Bài 2: Tính tổng chi phí vận chuyển
Mô tả: Công ty vận chuyển ghi nhận chi phí hàng ngày: [100, 150, 80, 200]. Tính tổng chi phí tuần bằng NumPy.
Yêu cầu:
Tạo mảng chi phí.
Dùng hàm np.sum() để tính tổng.
Đáp án mẫu:
import numpy as np
chi_phi = np.array([100, 150, 80, 200])
tong_chi_phi = np.sum(chi_phi)
print("Tổng chi phí:", tong_chi_phi)  # Kết quả: 530

In [3]:
import numpy as np
chi_phi_hang_ngay = np.array([100, 150, 80, 200])
tong_chi_phi = np.sum(chi_phi_hang_ngay)
print(tong_chi_phi)

530


Bài 3: So sánh doanh thu hai cửa hàng
Mô tả: Hai cửa hàng có doanh thu tuần: Cửa hàng A [10, 12, 8], Cửa hàng B [9, 15, 7]. Tính chênh lệch doanh thu từng ngày.
Yêu cầu:
Tạo hai mảng.
Dùng phép trừ element-wise để tính chênh lệch.
Đáp án mẫu:
import numpy as np
a = np.array([10, 12, 8])
b = np.array([9, 15, 7])
chenh_lech = a - b
print("Chênh lệch doanh thu:", chenh_lech)  # Kết quả: [1 -3 1]

In [7]:
import numpy as np
store_A = np.array([10, 12, 8])
store_B = np.array([9, 15, 7])
rev_chenh_lech = store_A - store_B
print(rev_chenh_lech)

[ 1 -3  1]


Bài 4: Tính trung bình điểm số học sinh
Mô tả: Điểm số 5 học sinh môn Toán: [7.5, 8.0, 6.5, 9.0, 7.0]. Tính điểm trung bình.
Yêu cầu:
Tạo mảng điểm số.
Dùng np.mean() để tính trung bình.
Đáp án mẫu:
import numpy as np
diem = np.array([7.5, 8.0, 6.5, 9.0, 7.0])
trung_binh = np.mean(diem)
print("Điểm trung bình:", trung_binh)  # Kết quả: 7.6

In [8]:
import numpy as np
diem_tb_toan = np.array([7.5, 8.0, 6.5, 9.0, 7.0])
tb_moi_hs = np.mean(diem_tb_toan)
print(tb_moi_hs)

7.6


Bài 5: Tạo bảng doanh thu 2D
Mô tả: Doanh thu 3 ngày của 2 cửa hàng: Cửa hàng 1 [5, 6, 7], Cửa hàng 2 [8, 9, 10]. Tạo mảng 2D.
Yêu cầu:
Tạo mảng 2D bằng np.array().
In mảng và kiểm tra shape và ndim.
Đáp án mẫu:
import numpy as np
doanh_thu_2d = np.array([[5, 6, 7], [8, 9, 10]])
print("Doanh thu 2D:\n", doanh_thu_2d)
print("Shape:", doanh_thu_2d.shape)  # (2, 3)
print("Số chiều:", doanh_thu_2d.ndim)  # 2

In [11]:
import numpy as np
rev = np.array([[5, 6, 7],[8, 9, 10]])
print(rev)
print(rev.shape)
print(rev.ndim)

[[ 5  6  7]
 [ 8  9 10]]
(2, 3)
2


Bài 6: Điều chỉnh giá sản phẩm
Mô tả: Giá 4 sản phẩm [100, 200, 150, 300] tăng 10%. Tính giá mới.
Yêu cầu:
Tạo mảng giá gốc.
Nhân mảng với 1.1 để tăng giá.
Đáp án mẫu:
import numpy as np
gia = np.array([100, 200, 150, 300])
gia_moi = gia * 1.1
print("Giá mới:", gia_moi)  # Kết quả: [110. 220. 165. 330.]

In [12]:
import numpy as np
old_price = np.array([100, 200, 150, 300])
new_price = old_price * 1.1
print(new_price)

[110. 220. 165. 330.]


Bài 7: Phân tích độ lệch chuẩn doanh thu
Mô tả: Doanh thu 5 ngày [1000, 1500, 800, 2000, 1200]. Tính độ lệch chuẩn để đánh giá biến động.
Yêu cầu:
Tạo mảng doanh thu.
Dùng np.std() và nhận xét (cao: biến động lớn, thấp: ổn định).
Đáp án mẫu:
import numpy as np
doanh_thu = np.array([1000, 1500, 800, 2000, 1200])
std = np.std(doanh_thu)
print("Độ lệch chuẩn:", std)  # Kết quả: ~435.89
print("Nhận xét: Biến động lớn" if std > 200 else "Ổn định")

In [19]:
import numpy as np
rev = np.array([1000, 1500, 800, 2000, 1200])
print(rev.std())
print("Biến động lớn" if rev.std() > 200 else "Ổn định")

419.52353926806063
Biến động lớn


Bài 8: Reshape dữ liệu khách hàng
Mô tả: Bạn có 6 giá trị chi tiêu của khách hàng [50, 60, 70, 80, 90, 100]. Chuyển thành mảng 2D (3 khách hàng, 2 ngày).
Yêu cầu:
Tạo mảng 1D.
Dùng reshape() để đổi thành 2D (3, 2).
Đáp án mẫu:
import numpy as np
chi_tieu = np.array([50, 60, 70, 80, 90, 100])
chi_tieu_2d = chi_tieu.reshape(3, 2)
print("Chi tiêu 2D:\n", chi_tieu_2d)  # [[50 60] [70 80] [90 100]]


In [22]:
import numpy as np
chi_tieu_1d = np.array([50, 60, 70, 80, 90, 100])
chi_tieu_2d = chi_tieu_1d.reshape(3,2)
print(chi_tieu_2d)

[[ 50  60]
 [ 70  80]
 [ 90 100]]


Bài 9: Phân tích giá cổ phiếu
Mô tả: Giá cổ phiếu 2 công ty qua 3 ngày: Công ty A [100, 105, 98], Công ty B [95, 102, 90]. Tính trung bình và độ lệch chuẩn theo từng công ty.
Yêu cầu:
Tạo mảng 2D.
Dùng np.mean() và np.std() với axis=1.
Đáp án mẫu:
import numpy as np
gia_cp = np.array([[100, 105, 98], [95, 102, 90]])
tb = np.mean(gia_cp, axis=1)
std = np.std(gia_cp, axis=1)
print("Trung bình:", tb)  # [101. 95.666]
print("Độ lệch chuẩn:", std)  # [2.94 4.92]

In [25]:
import numpy as np
gia_co_phieu = np.array([[100, 105, 98],[95, 102, 90]]) # Mảng gồm 2 hàng 3 cột - mỗi hàng là một công ty
gia_co_phieu_tb = np.mean(gia_co_phieu, axis=1) # Tính theo hàng ngang (axis=1) - tr.bình giá cổ phiếu mỗi cty
gia_co_phieu_std = np.std(gia_co_phieu, axis=1) # Tính theo hàng ngang (axis=1) - std giá cổ phiếu mỗi cty
print(gia_co_phieu_tb)
print(gia_co_phieu_std)

[101.          95.66666667]
[2.94392029 4.92160769]


Bài 10: Phát hiện outlier trong giao dịch
Mô tả: Dữ liệu giao dịch tuần [500, 600, 550, 2000, 700]. Tìm giao dịch bất thường (cách trung bình > 1.5 lần std).
Yêu cầu:
Tạo mảng giao dịch.
Tính mean, std, và dùng Z-score để tìm outlier.
Đáp án mẫu:
import numpy as np
giao_dich = np.array([500, 600, 550, 2000, 700])
mean = np.mean(giao_dich)
std = np.std(giao_dich)
outliers = giao_dich[np.abs(giao_dich - mean) > 1.5 * std]
print("Mean:", mean)  # 870
print("Std:", std)   # ~588
print("Outliers:", outliers)  # [2000]

In [37]:
import numpy as np
trans = np.array([500, 600, 550, 2500, 700])
trans_mean = np.mean(trans)
trans_std = np.std(trans)
# Sử dụng Z-score NumPy boolean indexing để tìm outliers
outliers = trans[np.abs(trans - trans_mean) > 1.5 * trans_std]
print(trans_mean)
print(trans_std)
print(outliers)

970.0
767.8541528180987
[2500]
